name: Core-v4 Tests

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Starting MongoDB
      run:  |
           if: [ "matrix.os == 'windows-latest']; then
                uses: supercharge/mongodb-github-action@1.3.0
           fi
    - run: npm run api-test
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: python setup.py
    - run: npm ci
    - run: cd api
    - run: npm ci
    - run: cd ..
    - run: npm run lint
    - run: npm run frontend-test
    - run: npm run build
