name: Core-v4 Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Starting MongoDB 
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: python setup.py
    - run: npm ci
    - run: cd api
    - run: npm ci
    - run: cd ..
    - run: npm run lint
    - run: npm run api-test
    - run: npm run frontend-test
    - run: npm run build
